### ISSUE TITLE
Unable to create custom ecl command

### ISSUE THREAD

**Issue by marco-manalo** [xored/rcptt.extensions.ecl#1]
I have already successfully created custom ecl command few months ago following this guide on how to create custom command . They are all working but now with the 2.4.1 Release,
i tried to add new custom ecl command and even the one that i have created already they are not working anymore. In the RCPTT IDE it shows in the content assist but when running it says that Scriptlet not found. I haven't changed any configuration for my build. I tried to build example project containing show-view command and its the same problem saying Scriptlet ShowView not found.

**Comment by akoptelov** [comment]
@DudaevAR, I'm still having troubles using this sample out of the box. The problem is with platform version range that is [3.5, 4.8) [here](https://github.com/xored/rcptt.extensions.ecl/blob/master/ide/plugins/org.eclipse.rcptt.extensions.updates/plugin.xml). That means that this extension is not injected into anything newer than Oxygen. Should I open a new issue, or is it OK to fix that here?
